# This is a basic workflow to help you get started with Actions

name: selenium siderunner tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
 
# defaults:
 # run:
   # working-directory: seleniumide-tests -beállítható ez?
  
# A workflow run is made up of one or more jobs that can run sequentially or in paralle
jobs:
  # This workflow contains a single job called "build"
 build:
    # The type of runner that the job will run on
  runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  - name: Check out repository code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: actions/checkout@v2
    
  - name: Docker building Conduit
    run:|
      docker-compose up -d    
  - name: Install dependencies
    run:|
      python -m pip install --upgrade pip
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
  - name: install Nodejs
    uses: actions/setup-node@v2
    with:
        node-version: '14'
        
  - name: Install Selenium Side Runner
    run:|
        npm install -g selenium-side-runner
        
  - name: Install Chrome
    run:|
        sudo apt install google-chrome-stable
        
  - name: Install seleniumbase
    run: pip install seleniumbase
    
  - name: Install chromedriver
    run:|
        seleniumbase install chromedriver
        
  - name: Run Tests registration.side
    run:|
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumside-tests/registration.side
  - name: Run Tests login.side.
    run:|
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumside-tests/login.side
  - name: Run Tests post.side
    run:|
        selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" seleniumside-tests/post.side
       

      
